### ISSUE TITLE
Watch included/extended files

### ISSUE THREAD

**Issue by lagoasoft-lucasschmidt** [redhotvengeance/browserify-plain-jade#1]
Hey man, thanks for the transform!

Do you know if there are any strategies available to make browserify watch the included/extended jade files? 

Thanks.

**Comment by redhotvengeance** [comment]
I don't think browserify has any built-in methods to watch files. I usually pair it with other solutions (like [Grunt](http://gruntjs.com/) or [Gulp](http://gulpjs.com/)) to get that functionality.

**Comment by lagoasoft-lucasschmidt** [comment]
Well, correct, I guess I was talking about https://github.com/substack/watchify

I need to investigate a bit how it actually works, so I can see if there is actually a solution for this. 

If I require a jade, it actually watches that single file. So, maybe there is a way somewhere. 

Thanks.

**Comment by redhotvengeance** [comment]
Ah, I haven't used watchify, so I can't help you there. If you find a good solution, feel free to update this thread.

**Comment by lagoasoft-lucasschmidt** [comment]
@redhotvengeance , it looks like this can be improved by emitting the `file` event. https://github.com/substack/watchify/issues/63

I will take a look at it later on, and if I can get anything working, I get back at u.

**Comment by redhotvengeance** [comment]
@lucastschmidt Sounds good. If you get something working, feel free to open a PR.

**Comment by lagoasoft-lucasschmidt** [comment]
Ok, @redhotvengeance, I already got it working, but the algorithm to detect jade dependencies is not that good, and I couldnt find a module that I could work with .... I will see if I implemented something later on. 

Possibly a separated module to get the dependencies, and then I can do a PR, but I dont know if you guys will want this, since it may decrease performance overall.

**Comment by lagoasoft-lucasschmidt** [comment]
Hey @redhotvengeance , I will see if I can add support, based on https://github.com/domenic/jadeify/pull/19 

Looks like a clean solution.

**Comment by redhotvengeance** [comment]
@lucastschmidt Sounds goods - looking forward to it.

**Comment by lagoasoft-lucasschmidt** [comment]
Ok, now I just did the change, we will be doing some tests around here, if its good enough, I will do a pull request.
